# Generated by Django 3.0.8 on 2021-01-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210112_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_Stamp',
            field=models.DateTimeField(),
        ),
    ]
