# Generated by Django 3.0.8 on 2021-01-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210114_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_User',
            new_name='post_Author',
        ),
    ]
