# Generated by Django 3.0.8 on 2021-01-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210119_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_Post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likePostid', to='network.Post'),
        ),
    ]
