# Generated by Django 3.0.8 on 2021-01-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210122_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
